# TODO: If you are running into any issues during startup, uncomment
# the following line.
# debug: true

# Using Jetty for the server, and only 5 threads to reduce the
# amount of memory required.
server:
  jetty:
    acceptors: 5

logging:
  pattern:
    console: "%d [%t] %-5p - %m%n"
spring:
  main:
    banner-mode: "off"
    allow-bean-definition-overriding: true
# When, or if, this project is upgraded to Spring Boot 2.2, this is documented
# as a way to shut off eagar initialization, which should increase startup
# performance of Spring Boot in PCF quite a bit.
#    lazy-initialization: true
